  let cert_path = "/usr/local/share/imaplet"
  let users_path = "/usr/local/share/imaplet/users"
  let config_path = "/usr/local/share/imaplet/imaplet.cf"
  let irmin_srv_exec = "/usr/local/bin/imaplet_irmin_store"
  let lmtp_srv_exec = "/usr/local/bin/imaplet_lmtp"
  let prx_srv_exec = "/usr/local/bin/imaplet_proxy"
