  let data_path = "/usr/local/share/imaplet"
  let bin_path = "/usr/local/bin"
  let users_path = "/usr/local/share/imaplet/users"
  let config_path = "/usr/local/share/imaplet/imaplet.cf"
  let smtp_srv_exec = "/usr/local/bin/imaplet_smtp"
